import { z } from "zod";
import {
  projectSortOptions,
  bookSortOptions,
  homeworkSortOptions,
  userSortOptions,
} from "../search.js";

export const conductorSearchSchema = z.object({
  query: z.object({
    searchQuery: z.string().min(1).max(200),
    bookLibrary: z.string().optional(),
    bookSubject: z.string().optional(),
    bookLocation: z.enum(["campus", "central"]).optional(),
    bookLicense: z.string().optional(),
    bookAuthor: z.string().optional(),
    bookCourse: z.string().optional(),
    bookPublisher: z.string().optional(),
    bookAffiliation: z.string().optional(),
    bookCID: z.string().optional(),
    assetLicense: z.string().optional(),
    assetOrg: z.string().optional(),
    assetFileType: z.string().optional(),
    projLocation: z.enum(['local', 'global']).optional(),
    projStatus: z.string().optional(),
    projSort: z.enum(projectSortOptions).optional(),
    bookSort: z.enum(bookSortOptions).optional(),
    hwSort: z.enum(homeworkSortOptions).optional(),
    userSort: z.enum(userSortOptions).optional(),
    booksPage: z.coerce.number().min(1).default(1),
    booksLimit: z.coerce.number().int().min(1).default(25),
    assetsPage: z.coerce.number().min(1).default(1),
    assetsLimit: z.coerce.number().int().min(1).default(25),
    projectsPage: z.coerce.number().min(1).default(1),
    projectsLimit: z.coerce.number().int().min(1).default(25),
    homeworkPage: z.coerce.number().min(1).default(1),
    homeworkLimit: z.coerce.number().int().min(1).default(25),
    usersPage: z.coerce.number().min(1).default(1),
    usersLimit: z.coerce.number().int().min(1).default(25),
  }),
});
