/**
 * @file Defines a Mongoose schema for storing access tokens that external Conductor API
 *  Clients use to perform requests on behalf of a user.
 * @author LibreTexts <info@libretexts.org>
 */
import mongoose from 'mongoose';

const AccessTokenSchema = new mongoose.Schema({
  /**
   * Access token generated by the system.
   */
  token: {
    type: String,
    required: true,
    index: true,
  },
  /**
   * UUID of the user the access token was issued on behalf of.
   */
  user: {
    type: String,
    required: true,
  },
  /**
   * Identifier of the external service the access token was issued for.
   */
  apiClientID: {
    type: String,
    required: true,
  },
  /**
   * Datetime the access token was issued.
   */
  issued: {
    type: Date,
    required: true,
  },
  /**
   * Seconds that the access token is valid for.
   */
  expiresIn: {
    type: Number,
    required: true,
  },
});

const AccessToken = mongoose.model('AccessToken', AccessTokenSchema);

export default AccessToken;
