//
// LibreTexts Conductor
// organization.js
// Mongoose Model
//

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const OrganizationSchema = new Schema({
    orgID: {                        // the organization's internal identifier string
        type: String,
        required: true
    },
    name: {                         // the organization's full name
        type: String,
        required: true
    },
    shortName: String,              // the organization's shortened name
    abbreviation: String,           // the organization's abbreviation
    aliases: [String],              // other names the organization may be referred to by (internal use)
    coverPhoto: String,             // the organization's large "cover photo"
    largeLogo: String,              // the organization's large/main logo
    mediumLogo: String,             // the organization's medium/secondary logo
    smallLogo: String,              // the organization's smallest logo or icon
    aboutLink: String,              // the organization's "About" page link,
    commonsHeader: String,          // the header text displayed on Campus Commons main page (optional)
    commonsMessage: String,         // the welcome text displayed on Campus Commons main page (optional),
    mainColor: String,              // the hex representation of the organization's main branding color
    defaultProjectLead: String      // the default Lead for autogenerated Projects in the Organization (LibreTexts-specific)
}, {
    timestamps: true
});

const Organization = mongoose.model('Organization', OrganizationSchema);

module.exports = Organization;
