name: Release SemVer and Build Docker Image

on: workflow_dispatch

jobs:
  check_authorization:
    name: Check authorization to release new version
    runs-on: ubuntu-latest
    outputs:
      isAuthorized: ${{ steps.check-auth.outputs.is_authorized }}
    steps:
      - name: check-auth
        id: check-auth
        run: echo "is_authorized=${{ contains(secrets.DEPLOYMENT_AUTHORIZED_USERS, github.triggering_actor) }}" >> $GITHUB_OUTPUT
  release:
    name: Release new semantic version
    needs: check_authorization
    if: needs.check_authorization.outputs.isAuthorized == 'true'
    runs-on: ubuntu-latest
    outputs:
      didRelease: ${{ steps.semver.outputs.new_release_published }}
      newVersion: ${{ steps.semver.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.LIBREBOT_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: libretexts-bot
          GIT_AUTHOR_EMAIL: dev@libretexts.org
          GIT_COMMITTER_NAME: libretexts-bot
          GIT_COMMITTER_EMAIL: dev@libretexts.org
  build:
    name: Build Docker image
    needs: release
    if: needs.release.outputs.didRelease == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/libretexts/conductor:${{ needs.release.outputs.newVersion }}